Merge branch 'dev' into gemtalk
(cherry picked from commit 59fb4716269fa5d5bb9187feb5b6c127c36aa52b)

Conflicts:
	bin/installTodeStone
	bin/startStone
	bin/stopStone
	tode/server/scripts/installGLASS1.ws
	tode/server/scripts/installMetacello.ws
	tode/server/scripts/installTode.ws

diff --git a/bin/createTodeImage b/bin/createTodeImage
--- a/bin/createTodeImage
+++ b/bin/createTodeImage
@@ -1,63 +1,44 @@
 #! /bin/bash
-
 #=========================================================================
 # Copyright (c) 2014 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
-#
-# Name - createTodeImage
-#
-# Purpose - create the tODE client image
-#
-# Examples
-#   createTodeImage -h
-#   createTodeImage -p _0
-#   createTodeImage
-#
 #=========================================================================
 
-# help function
-function display_help() {
-  echo ""
-  echo "USAGE: $(basename $0) [-h] [-p <postfix]"
-  echo "Create the tODE client image. Used for running pharo-based scripts"
-  echo "and for running the tODE client UI."
-  echo ""
-  echo "OPTIONS"
-  echo "  -h "
-  echo "    display help"
-  echo "  -p <postfix>"
-  echo "    Append <postfix> to end of image name. Useful for creating"
-  echo "    multiple tode client images."
-  echo ""
-  echo "EXAMPLES"
-  echo "  $(basename $0) -h"
-  echo "  $(basename $0) -p _0"
-  echo "  $(basename $0)"
-  echo ""  
+usage() {
+  cat <<HELP
+USAGE: $(basename $0) [-h] [-p <postfix]
+Create the tODE client image. Used for running pharo-based scripts
+and for running the tODE client UI.
+
+OPTIONS
+  -h 
+    display help
+  -p <postfix>
+    Append <postfix> to end of image name. Useful for creating
+    multiple tode client images.
+
+EXAMPLES
+  $(basename $0) -h
+  $(basename $0) -p _0
+  $(basename $0)
+
+HELP
 }
 
-postFix=""
-while getopts "hp:" OPT ; do
-  case "$OPT" in
-    h) 
-      display_help
-      exit 1
-      ;;
-    p)
-      postFix="${OPTARG}"
-      ;;
-    *)
-      display_help
-      exit 1
-      ;;
-  esac
-done
-
+set -e # exit on error
 if [ "${GS_HOME}x" = "x" ] ; then
   echo "the GS_HOME environment variable needs to be defined"
   exit 1
 fi
 
-# create tODE client
+postFix=""
+while getopts "hp:" OPT ; do
+  case "$OPT" in
+    h) usage; exit 0;;
+    p) postFix="${OPTARG}";;
+    *) usage; exit 1;;
+  esac
+done
+
 pharo=$GS_HOME/pharo
 if [ -e $pharo/todeClient${postFix}.image ] ; then
   echo "todeClient already installed"
@@ -80,21 +61,9 @@ cat - > $pharo/todeLoad.st << EOF
 EOF
 
 $pharo/pharo $pharo/todeClientTmp.image st --quit --save $pharo/todeLoad.st
-if [[ $? != 0 ]] ; then
-  echo "createTodeImage[Error]: failed loading tode client"
-  exit 1
-fi
 
 $pharo/pharo $pharo/todeClientTmp.image save todeClient${postFix}
-if [[ $? != 0 ]] ; then
-  echo "createTodeImage[Error]: failed saving tode client"
-  rm -f todeClient*
-  exit 1
-fi
 
 rm -f todeClientTmp.*
 echo
 echo "tODEClient${postFix} image creation complete"
-
-# End of script
-exit 0
diff --git a/bin/installClient b/bin/installClient
--- a/bin/installClient
+++ b/bin/installClient
@@ -1,66 +1,39 @@
 #! /bin/bash
-
 #=========================================================================
 # Copyright (c) 2014 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
-#
-# Name - installClient
-#
-# Purpose - Install GemStone (specified gs-version), Pharo, build tODE client
-#           image and launch the tODE client.
-#
-# Examples
-#   installClient -h
-#   installClient 3.2.1
-#
 #=========================================================================
 
-# help function
-function display_help() {
-  echo ""
-  echo "USAGE: $(basename $0) [-h] <gemstone-version>"
-  echo " Create a todeClient image on a remote machine. Runs the installGemstone (to acquire gci"
-  echo "libraries), createTodeImage and todeClient scripts."
-  echo ""
-  echo "OPTIONS"
-  echo "  -h display help"
-  echo ""
-  echo "EXAMPLES"
-  echo "   $(basename $0) -h"
-  echo "   $(basename $0) 3.2.1"
-  echo ""
+usage() {
+  cat <<HELP
+
+USAGE: $(basename $0) [-h] <gemstone-version>
+ Create a todeClient image on a remote machine. Runs the installGemstone (to acquire gci
+libraries), createTodeImage and todeClient scripts.
+
+OPTIONS
+  -h display help
+
+EXAMPLES
+   $(basename $0) -h
+   $(basename $0) 3.2.1
+
+HELP
 }
 
-while getopts "h" OPT ; do
-  case "$OPT" in
-    h) 
-      display_help
-      exit 1
-      ;;
-    *)
-      display_help
-      exit 1
-      ;;
-  esac
-done
+set -e # exit on error
+if [ "${GS_HOME}x" = "x" ] ; then
+  echo "the GS_HOME environment variable needs to be defined"; exit 1
+fi
+source ${GS_HOME}/bin/shFunctions
+getOpts_help $@
 
-if [ "$1x" = "x" ] ; then
-  display_help
-  exit 1
+if [ $# -ne 1 ]; then
+  usage; exit 1
 fi
 gsvers="$1"
 
-if [ "${GS_HOME}x" = "x" ] ; then
-  echo "the GS_HOME environment variable needs to be defined"
-  exit 1
-fi
-
 $GS_HOME/bin/installGemStone $gsvers
-if [[ $? != 0 ]] ; then exit 1; fi
 
 $GS_HOME/bin/createTodeImage
-if [[ $? != 0 ]] ; then exit 1; fi
 
 $GS_HOME/bin/todeClient
-
-# End of script
-exit 0
diff --git a/bin/installGci b/bin/installGci
--- a/bin/installGci
+++ b/bin/installGci
@@ -1,63 +1,38 @@
 #! /bin/bash
-
 #=========================================================================
 # Copyright (c) 2014 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
-#
-# Name - installGci 
-#
-# Purpose - Install gemstone gci libraries from the specied gemstone
-#           release into the pharo vm
-#
-# Examples
-#   installGci -h
-#   installGci <gs-version>
-#
 #=========================================================================
 
-# help function
-function display_help() {
-  echo ""
-  echo "USAGE: $(basename $0) [-h] <gemstone-version>"
-  echo "Copy the gci libraries for the given GemStone version to the"
-  echo "$GS_HOME/pharo directory."
-  echo ""
-  echo "OPTIONS"
-  echo "  -h display help"
-  echo ""
-  echo "EXAMPLES"
-  echo "   $(basename $0) -h"
-  echo "   $(basename $0) 3.2.1"
-  echo ""
+usage() {
+  cat <<HELP
+USAGE: $(basename $0) [-h] <gemstone-version>
+Copy the gci libraries for the given GemStone version to the
+$GS_HOME/pharo directory.
+
+OPTIONS
+  -h display help
+
+EXAMPLES
+   $(basename $0) -h
+   $(basename $0) 3.2.1
+
+HELP
 }
 
-while getopts "h" OPT ; do
-  case "$OPT" in
-    h) 
-      display_help
-      exit 1
-      ;;
-    *)
-      display_help
-      exit 1
-      ;;
-  esac
-done
-
-if [ "$1x" = "x" ] ; then
-  display_help
-  exit 1
-fi 
-vers="$1"
+set -e # exit on error
 if [ "${GS_HOME}x" = "x" ] ; then
-  echo "the GS_HOME environment variable needs to be defined"
-  exit 1
+  echo "the GS_HOME environment variable needs to be defined"; exit 1
 fi
+source ${GS_HOME}/bin/shFunctions
+getOpts_help $@
+
+if [ $# -ne 1 ]; then
+  usage; exit 1
+fi
+vers="$1"
+
 echo "Copying gci files to pharo"
-
 pharo_vm=$GS_HOME/pharo/pharo-vm
-
-
-#    Copy the gci libraries to the Pharo vm
 if [ ! -e "$pharo_vm" ]; then
   echo "Install Pharo"
   $GS_HOME/bin/installPharo
@@ -80,6 +55,3 @@ case "$PLATFORM" in
     cp $gs_product/lib32/lib* $pharo_vm/Pharo.app/Contents/MacOS/Plugins
   ;;
 esac
-
-# End of script
-exit 0
diff --git a/bin/installGemStone b/bin/installGemStone
--- a/bin/installGemStone
+++ b/bin/installGemStone
@@ -23,6 +23,7 @@
 #    Add shared memory setup to /etc/sysctl.conf
 #    Add GemStone netldi service port to /etc/services
 #    Download the GemStone product zipfile
+#    Create /opt/gemstone and required subdirectories
 #    Uncompress the GemStone zipfile into $GS_HOME/products
 #    Copy the initial GsDevKit repository to data directory
 #    Copy the gci libraries to the Pharo vm (install Pharo if necessary)
@@ -30,37 +31,33 @@
 #=========================================================================
 
 # help function
-function display_help() {
-  echo ""
-  echo "USAGE: $(basename $0) [-h] <gemstone-version>"
-  echo "Download and install the given GemStone version. Will make sure that"
-  echo "shared memory is correctly configuration on your server. Performs some"
-  echo "operations as `root` using sudo."
-  echo ""
-  echo "OPTIONS"
-  echo "  -h display help"
-  echo ""
-  echo "EXAMPLES"
-  echo "  $(basename $0) -h"
-  echo "  $(basename $0) 3.2.0"
-  echo ""
+usage() {
+ cat <<HELP
+USAGE: $(basename $0) [-h] <gemstone-version>
+Download and install the given GemStone version. Will make sure that
+shared memory is correctly configuration on your server. Performs some
+operations as `root` using sudo.
+
+OPTIONS
+  -h display help
+
+EXAMPLES
+  $(basename $0) -h
+  $(basename $0) 3.2.0
+
+HELP
 }
 
+set -e # exit on error
 while getopts "h" OPT ; do
   case "$OPT" in
-    h) 
-      display_help
-      exit 1
-      ;;
-    *)
-      display_help
-      exit 1
-      ;;
+    h) usage ; exit 0 ;;
+    *) usage ; exit 1 ;;
   esac
 done
 
 if [ "$1x" = "x" ] ; then
-  display_help
+  usage
   exit 1
 fi 
 vers="$1"
@@ -276,6 +273,18 @@ else
     echo "to replace it, remove or rename it and rerun this script"
 fi
 
+# Create some directories that GemStone expects; make them writable
+echo "[Info] Creating /opt/gemstone directory"
+if [ ! -e /opt/gemstone ]
+    then
+    sudo mkdir -p /opt/gemstone /opt/gemstone/log /opt/gemstone/locks
+    sudo chown $USER:${GROUPS[0]} /opt/gemstone /opt/gemstone/log /opt/gemstone/locks
+    sudo chmod 770 /opt/gemstone /opt/gemstone/log /opt/gemstone/locks
+else
+    echo "[Warning] /opt/gemstone directory already exists"
+    echo "to replace it, remove or rename it and rerun this script"
+fi
+
 # Unzip the downloaded archive into $GS_HOME/gemstone/products/
 echo "[Info] Uncompressing GemStone archive into $GS_HOME/gemstone/products/"
 gs_product=$GS_HOME/gemstone/products/$gsvers
@@ -342,6 +351,20 @@ echo "[Info] Finished $gsvers installation on $machine_name"
 echo ""
 echo "[Info] GemStone version information:"
 cat $gs_product/version.txt
+
+if [ "${GS_TRAVIS}x" != "x" ] ; then
+  # running on travis server - have to use a custom key file
+  case "$vers" in
+    2.4.*) keyName="GemStone64Bit2.4.0-x86_64.Linux.key" ;;
+    3.0.1) keyName="GemStone64Bit3.0.0-x86_64.Linux.key" ;;
+    3.1.*) keyName="GemStone64Bit3.1.0-x86_64.Linux.key" ;;
+    3.2.*) keyName="GemStone64Bit3.2.0-x86_64.Linux.key" ;;
+    *) echo "No travis license for GemStone $vers"; exit 1;;
+  esac
+  chmod +w  $gs_product/seaside/etc/gemstone.key
+  echo "Copying $GS_HOME/travis/$keyName to $gs_product/seaside/etc/gemstone.key"
+  cp $GS_HOME/travis/$keyName $gs_product/seaside/etc/gemstone.key
+fi
 
 # If we can determine any IPv4 addresses, print them out. Otherwise be silent.
 if [[ -x /sbin/ifconfig && `/sbin/ifconfig -a | grep -sc " inet addr:.*Bcast"` -gt 0 ]]
diff --git a/bin/restoreFromBackup b/bin/restoreFromBackup
--- a/bin/restoreFromBackup
+++ b/bin/restoreFromBackup
@@ -1,63 +1,35 @@
 #! /bin/bash
-
 #=========================================================================
 # Copyright (c) 2014 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
-#
-# Name - restoreFromBackup
-#
-# Purpose - Restore from backup for the given stone using the named
-#           backup file from the stone backups directory
-#
-# Examples
-#   restoreFromBackup -h
-#   restoreFromBackup kit home.dbf
-#
 #=========================================================================
 
-# help function
-function display_help() {
-  echo ""
-  echo "USAGE: $(basename $0) [-h] <stone-name> <backup-file>"
-  echo "Restore a backup on the given stone."
-  echo ""
-  echo "OPTIONS"
-  echo "  -h display help"
-  echo ""
-  echo "EXAMPLES"
-  echo "  $(basename $0) -h"
-  echo "  $(basename $0) kit home.dbf"
-  echo ""
+usage() {
+  cat <<HELP
+USAGE: $(basename $0) [-h] <stone-name> <backup-file>
+Restore a backup on the given stone.
+
+OPTIONS
+  -h display help
+
+EXAMPLES
+  $(basename $0) -h
+  $(basename $0) kit home.dbf
+
+HELP
 }
 
-while getopts "h" OPT ; do
-  case "$OPT" in
-    h) 
-      display_help
-      exit 1
-      ;;
-    *)
-      display_help
-      exit 1
-      ;;
-  esac
-done
-
-if [ "$1x" = "x" ] ; then
-  display_help
-  exit 1
+set -e # exit on error
+if [ "${GS_HOME}x" = "x" ] ; then
+  echo "the GS_HOME environment variable needs to be defined"; exit 1
 fi
-if [ "$2x" = "x" ] ; then
-  display_help
-  exit 1
-fi
+source ${GS_HOME}/bin/shFunctions
+getOpts_help $@
 
+if [ $# -ne 2 ]; then
+  usage; exit 1
+fi
 stoneName=$1
 backupFile=$2
-
-if [ "${GS_HOME}x" = "x" ] ; then
-  echo "the GS_HOME environment variable needs to be defined"
-  exit 1
-fi
 
 echo "Restoring backup for stone: $stoneName using: $backupFile"
 
@@ -69,7 +41,3 @@ popd $stonePath >& /dev/null
 
 # do restore
 $GS_HOME/bin/tode restoreFromBackup $stoneName $backupFile
-if [[ $? != 0 ]] ; then exit 1; fi
-
-# End of script
-exit 0
diff --git a/bin/startNetldi b/bin/startNetldi
--- a/bin/startNetldi
+++ b/bin/startNetldi
@@ -1,56 +1,34 @@
 #! /bin/bash
-
 #=========================================================================
 # Copyright (c) 2014 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
-#
-# Name - startnetldi
-#
-# Purpose - Start the netldi process for the named stone
-#
-# Examples
-#   startnetldi -h
-#   startnetldi kit
-#
 #=========================================================================
 
-# help function
-function display_help() {
-  echo ""
-  echo "USAGE: $(basename $0) [-h] <stone-name>"
-  echo " Start the netldi process for the given stone."
-  echo ""
-  echo "OPTIONS"
-  echo "  -h display help"
-  echo ""
-  echo "EXAMPLES"
-  echo "  $(basename $0) -h"
-  echo "  $(basename $0) kit"
-  echo ""
+usage() {
+  cat <<HELP
+USAGE: $(basename $0) [-h] <stone-name>
+ Start the netldi process for the given stone.
+
+OPTIONS
+  -h display help
+
+EXAMPLES
+  $(basename $0) -h
+  $(basename $0) kit
+
+HELP
 }
 
-while getopts "h" OPT ; do
-  case "$OPT" in
-    h) 
-      display_help
-      exit 1
-      ;;
-    *)
-      display_help
-      exit 1
-      ;;
-  esac
-done
+set -e # exit on error
+if [ "${GS_HOME}x" = "x" ] ; then
+  echo "the GS_HOME environment variable needs to be defined"; exit 1
+fi
+source ${GS_HOME}/bin/shFunctions
+getOpts_help $@
 
-if [ "$1x" = "x" ] ; then
-  display_help
-  exit 1
+if [ $# -ne 1 ]; then
+  usage; exit 1
 fi
 stoneName=$1
-
-if [ "${GS_HOME}x" = "x" ] ; then
-  echo "the GS_HOME environment variable needs to be defined"
-  exit 1
-fi
 
 echo "starting netldi $stoneName"
 
@@ -61,7 +39,3 @@ source $stonePath/stone.env
 popd $stonePath >& /dev/null
 
 $GS_HOME/bin/tode startnetldi $stoneName
-if [[ $? != 0 ]] ; then exit 1; fi
-
-# End of script
-exit 0
diff --git a/bin/startStatmonitor b/bin/startStatmonitor
--- a/bin/startStatmonitor
+++ b/bin/startStatmonitor
@@ -1,64 +1,37 @@
 #! /bin/bash
-
 #=========================================================================
 # Copyright (c) 2014 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
-#
-# Name - startStatmonitor
-#
-# Purpose - Start statmonitor for the named stone. Two statmonitors are 
-#           started. One that collects a sample every second and is 
-#           restarted every hour. One that collects a sample once a 
-#           minute and is restarted once a day.
-#
-# Examples
-#   startStatmonitor -h
-#   startStatmonitor kit
-#
 #=========================================================================
 
-# help function
-function display_help() {
-  echo ""
-  echo "USAGE: $(basename $0) [-h] <stone-name>"
-  echo "Start statmonitor for the given stone. Two statmonitors are"
-  echo "started. One that collects a sample every second and is"
-  echo "restarted every hour. One that collects a sample once a"
-  echo "minute and is restarted once a day."
-  echo ""
-  echo "OPTIONS"
-  echo "  -h display help"
-  echo ""
-  echo "EXAMPLES"
-  echo "  $(basename $0) -h"
-  echo "  $(basename $0) kit"
-  echo ""
+usage() {
+  cat <<HELP
+USAGE: $(basename $0) [-h] <stone-name>
+Start statmonitor for the given stone. Two statmonitors are
+started. One that collects a sample every second and is
+restarted every hour. One that collects a sample once a
+minute and is restarted once a day.
+
+OPTIONS
+  -h display help
+
+EXAMPLES
+  $(basename $0) -h
+  $(basename $0) kit
+
+HELP
 }
 
-while getopts "h" OPT ; do
-  case "$OPT" in
-    h) 
-      display_help
-      exit 1
-      ;;
-    *)
-      display_help
-      exit 1
-      ;;
-  esac
-done
+set -e # exit on error
+if [ "${GS_HOME}x" = "x" ] ; then
+  echo "the GS_HOME environment variable needs to be defined"; exit 1
+fi
+source ${GS_HOME}/bin/shFunctions
+getOpts_help $@
 
-if [ "$1x" = "x" ] ; then
-  display_help
-  exit 1
+if [ $# -ne 1 ]; then
+  usage; exit 1
 fi
 stoneName=$1
-
-if [ "${GS_HOME}x" = "x" ] ; then
-  echo "the GS_HOME environment variable needs to be defined"
-  exit 1
-fi
-
-echo "starting statmonitors for $stoneName"
 
 # set up stone environment
 stonePath=$GS_HOME/gemstone/stones/$stoneName
@@ -69,10 +42,5 @@ popd $stonePath >& /dev/null
 # start the statmonitors
 cd $stonePath/stats/1-second
 $stonePath/product/bin/statmonitor $stoneName -Arzq -h 1 -i 1 -u 0 &
-if [[ $? != 0 ]] ; then exit 1; fi
 cd ../60-second
 $stonePath/product/bin/statmonitor $stoneName -Arzq -h 24 -i 60 -u 0 &
-if [[ $? != 0 ]] ; then exit 1; fi
-
-# End of script
-exit 0
diff --git a/bin/updateTodeImage b/bin/updateTodeImage
--- a/bin/updateTodeImage
+++ b/bin/updateTodeImage
@@ -1,54 +1,36 @@
 #! /bin/bash
-
 #=========================================================================
 # Copyright (c) 2014 GemTalk Systems, LLC <dhenrich@gemtalksystems.com>.
-#
-# Name - updateTodeImage
-#
-# Purpose - Update the tODE client image
-#
-# Examples
-#   updateTodeImage -h
-#   updateTodeImage -p _0
-#   updateTodeImage
-#
 #=========================================================================
 
-# help function
-function display_help() {
-  echo ""
-  echo "USAGE: $(basename $0) [-h]] [-p <postfix>]"
-  echo "Update the tODE client image."
-  echo ""
-  echo "OPTIONS"
-  echo "  -h "
-  echo "    display help"
-  echo "  -p <postfix>"
-  echo "   Update the tode client image created with a matching postfix."
-  echo ""
-  echo "EXAMPLES"
-  echo "  $(basename $0) -h"
-  echo "  $(basename $0)"
-  echo ""
+usage() {
+  cat <<HELP
+USAGE: $(basename $0) [-h]] [-p <postfix>]
+Update the tODE client image.
+
+OPTIONS
+  -h 
+    display help
+  -p <postfix>
+   Update the tode client image created with a matching postfix.
+
+EXAMPLES
+  $(basename $0) -h
+  $(basename $0)
+
+HELP
 }
 
 postFix=""
 while getopts "hp:" OPT ; do
   case "$OPT" in
-    h) 
-      display_help
-      exit 1
-      ;;
-    p)
-      postFix="${OPTARG}"
-      ;;
-    *)
-      display_help
-      exit 1
-      ;;
+    h) usage; exit 0 ;;
+    p) postFix="${OPTARG}" ;;
+    *) usage; exit 1 ;;
   esac
 done
 
+set -e # exit on error
 if [ "${GS_HOME}x" = "x" ] ; then
   echo "the GS_HOME environment variable needs to be defined"
   exit 1
@@ -74,21 +56,9 @@ cat - > $pharo/todeLoad.st << EOF
 EOF
 
 $pharo/pharo $pharo/todeClientTmp.image st --quit --save $pharo/todeLoad.st
-if [[ $? != 0 ]] ; then
-  echo "updateTodeImage[Error]: failed loading tode client"
-  exit 1
-fi
 
 $pharo/pharo $pharo/todeClientTmp.image save todeClient${postFix}
-if [[ $? != 0 ]] ; then
-  echo "updateTodeImage[Error]: failed saving tode client"
-  rm -f todeClient*
-  exit 1
-fi
 
 rm -f todeClientTmp.*
 echo
 echo "tODEClient${postFix} image update complete"
-
-# End of script
-exit 0
